global using Microsoft.Extensions.Logging;
global using Sora.Core.Types;
global using Sora.Core.Enums;
global using MatchType = Sora.Core.Enums.MatchType;
global using Sora.Entities;
global using Sora.Entities.Segments;
global using Sora.Entities.Message;
global using Sora.Entities.Events;
global using Sora.Entities.Info;
global using Sora.Entities.Interfaces;
global using Sora.Adapter.Milky;
global using Sora.Adapter.OneBot11;
global using Sora.Command;
global using Sora.Command.Attributes;
global using Sora.Command.Matching;
global using Sora.Tests.Helpers;